version: '3.8'

services:
  ai-photo:
    build: .
    ports:
      - "8109:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 114.114.114.114
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3 

networks:
  app-network:
    driver: bridge 